В информационный лог добавлен вывод используемого для запуска команд исполняемого файла платформы
oscript-library/v8runner pull request #131
Opened 2021-01-18 15:49 UTC by AlexPCRus

В информационном логе при запуске команд отсутствует вывод используемой версии платформы. Предлагаю исправить эту неинформативность :)

2021-01-19 07:24 UTC, EvilBeaver requested changes

2021-01-19 07:24 UTC, EvilBeaver commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
Только не надо "Информация". Это же библиотека, она используется разными приложениями. Автор приложения может не хотеть выводить эту строку, но не сможет повлиять. Пусть будет Отладка

2021-01-19 07:24 UTC, EvilBeaver commented on src/v8runner.os
> +		Лог.Информация("Использую платформу " + мПутьКПлатформе1С);
Аналогично тут. А "Ошибка" ниже - пусть остается

2021-01-19 10:31 UTC, AlexPCRus commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
В отладке масса сообщений от плагинов :( Среди них теряется. Может быть какой-нибудь параметр? Или это еще сложнее?

2021-01-19 10:32 UTC, nixel2007 commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
Можно конфигурировать лог так, чтобы выводить только конкретное имя лога. Подробнее в ридми logos. Но в целом я тоже рекомендую не добавлять в либы какой-либо "информационный" вывод.

2021-01-19 10:48 UTC, AlexPCRus commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
Я посмотрю и отпишусь, спасибо за наводку.

2021-01-19 11:23 UTC, EvilBeaver commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
Да, отладочные логи можно фильтровать по имени лога, а вот информационные от библиотек засоряют вывод использующего приложения.

2021-01-19 16:54 UTC, AlexPCRus commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
Это конечно не так удобно, потому что v8runner выводит достаточно много отладочной информации :) и там есть в целом указание на путь к найденному выполняемому файлу платформы. Поэтому я у себя оставлю наверное в информации, а в PR исправлю на отладку.
Тогда получится что-то вроде:
ОТЛАДКА - [oscript.lib.v8runner] - Ищу платформу 8.3.17
ОТЛАДКА - [oscript.lib.v8runner] - Использую платформу C:\Program Files (x86)\1Cv8\8.3.17.1549\bin\1cv8.exe
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой /F"C:\Users\1\Documents\1C\SmallBusinessDemo1"
ОТЛАДКА - [oscript.lib.v8runner] - ИмяПользователя <Абдулов (директор)>
ОТЛАДКА - [oscript.lib.v8runner] - Пароль не задан
ИНФОРМАЦИЯ - Выполняю тесты  с помощью фреймворка Vanessa-ADD (Vanessa Automation Driven Development) - C:\Temp
ИНФОРМАЦИЯ - Выполняю команду/действие в режиме 1С:Предприятие
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой /F"C:\Users\1\Documents\1C\SmallBusinessDemo1"
ОТЛАДКА - [oscript.lib.v8runner] - ИмяПользователя <Абдулов (директор)>
ОТЛАДКА - [oscript.lib.v8runner] - ПутьКТонкомуКлиенту1С: Путь платформы 1С <>
ОТЛАДКА - [oscript.lib.v8runner] - ПутьКТонкомуКлиенту1С: вычислили Путь платформы 1С <C:\Program Files (x86)\1Cv8\8.3.17.1549\bin\1cv8.exe>
ОТЛАДКА - [oscript.lib.v8runner] - ПутьКТонкомуКлиенту1С: получили путь к тонкому клиенту 1С <C:\Program Files (x86)\1Cv8\8.3.17.1549\bin\1cv8c.exe>

или в случае ошибки:
ОТЛАДКА - [oscript.lib.v8runner] - Ищу платформу 8.3.20
ОШИБКА - [oscript.lib.v8runner] - Не найдена платформа 8.3.20
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой /F"C:\Users\1\Documents\1C\SmallBusinessDemo1"
ОТЛАДКА - [oscript.lib.v8runner] - ИмяПользователя <Абдулов (директор)>
ОТЛАДКА - [oscript.lib.v8runner] - Пароль не задан
ИНФОРМАЦИЯ - Выполняю тесты  с помощью фреймворка Vanessa-ADD (Vanessa Automation Driven Development) - C:\Temp
ИНФОРМАЦИЯ - Выполняю команду/действие в режиме 1С:Предприятие
ОТЛАДКА - [oscript.lib.v8runner] - КлючСоединенияСБазой /F"C:\Users\1\Documents\1C\SmallBusinessDemo1"
ОТЛАДКА - [oscript.lib.v8runner] - ИмяПользователя <Абдулов (директор)>
ОТЛАДКА - [oscript.lib.v8runner] - ПутьКТонкомуКлиенту1С: Путь платформы 1С <>
ОТЛАДКА - [oscript.lib.v8runner] - ПутьКТонкомуКлиенту1С: вычислили Путь платформы 1С <>
ОШИБКА - Причина ошибки:
Не установлен тонкий клиент
Вывод от 1С:Предприятие:

КРИТИЧНАЯОШИБКА - {Модуль C:\Program Files\OneScript\lib\vanessa-runner\oscript_modules\v8runner\src\v8runner.os / Ошибка в строке: 1594 / Не установлен тонкий клиент}

тут уже непонятно - надо ли дублировать вывод пути к исполняемому файлу? может быть ограничиться строкой "Ищу платформу: ХХХ"?

2021-01-19 17:05 UTC, EvilBeaver commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
Вы у себя можете сделать отдельный logos-аппендер для лога v8runner и в нем это перехватить, например.

2021-01-19 17:18 UTC, AlexPCRus commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
Да, но я же могу отбор делать только по уровню лога, правильно? Или мне прямо надо написать аналог ВыводЛогаВКонсоль и в нем уже фильтровать сообщения?
Пока остановился на простом set LOGOS_CONFIG=logger.oscript.lib.v8runner=DEBUG
И что собственно делать с PR? :)

2021-01-19 17:46 UTC, AlexPCRus commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
В logos appender расковырял, но это сложнее, чем две строчки в v8runner поменять :)

2021-01-19 21:51 UTC, EvilBeaver commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
> И что собственно делать с PR? :)

Исправить на Отладка - и вливаем

2021-01-20 05:37 UTC, AlexPCRus commented on src/v8runner.os
> +		Лог.Информация("Использую платформу " + мПутьКПлатформе1С);
Готово

2021-01-20 05:37 UTC, AlexPCRus commented on src/v8runner.os
> +	Лог.Информация("Ищу платформу " + ВерсияПлатформы);
Готово

2021-01-21 16:15 UTC, merged