Обработка списка файлов -listFile для /LoadConfigFromFiles
oscript-library/v8runner pull request #134
Opened 2021-06-01 13:59 UTC by infina15

Функция удаляет строки модулей форм из списка файлов, оставляя только файлы .xml форм. Платформа выдает ошибку "Неизвестный объект метаданных Document.<ИмяДокумента>.Form.ФормаДокумента.Ext", если передать строку "*\Ext\Form\Module.bsl". Такие строки следует заменять на "*.xml", команда /LoadConfigFromFiles вместе с .xml файлом сама затянет модуль формы.

2021-06-01 14:03 UTC, EvilBeaver commented on src/v8runner.os
> +			ПутьКСпискуФайловЗагрузки_Обработанный = ПолучитьОбработанныйФайлСписка(ПутьКСпискуФайловЗагрузки);
не очень понял, где потом используется эта переменная?

2021-06-01 14:05 UTC, infina15 commented on src/v8runner.os
> +			ПутьКСпискуФайловЗагрузки_Обработанный = ПолучитьОбработанныйФайлСписка(ПутьКСпискуФайловЗагрузки);
уже увидел, щас поправлю

2021-06-01 14:42 UTC, EvilBeaver requested changes

2021-06-01 14:42 UTC, EvilBeaver commented on src/v8runner.os
> +			Параметры.Добавить(СтрШаблон("-listFile %1", ОбернутьВКавычки(ПутьКСпискуФайловЗагрузки_Обработанный)));
Кажется, что нужно еще и удаление "обработанного" файла после отработки команды. Клиент, использующий v8runner не знает, что тот создает копию переданного в метод файла. Этот файл - ответственность самого v8runner и v8runner должен за собой чистить. Воспользуйтесь библиотекой tempfiles для этого.

2021-06-01 14:43 UTC, EvilBeaver commented on src/v8runner.os
> +	ОбработанныйФайл = ПолучитьИмяВременногоФайла(".txt");
лучше использовать ВременныеФайлы, она чистит темпы самостоятельно

2021-06-01 15:44 UTC, infina15 commented on src/v8runner.os
> +			Параметры.Добавить(СтрШаблон("-listFile %1", ОбернутьВКавычки(ПутьКСпискуФайловЗагрузки_Обработанный)));
верно, я почему-то думал что само удаляется как в 1С
Спасибо

2021-06-01 15:45 UTC, infina15 commented on src/v8runner.os
> +	ОбработанныйФайл = ПолучитьИмяВременногоФайла(".txt");
сделал

2021-06-01 18:03 UTC, EvilBeaver requested changes

2021-06-01 18:41 UTC, infina15 commented
> А Экспорт точно нужен? 

да пусть был бы, вдруг кто захочет отдельно воспользоваться

2021-06-01 18:44 UTC, infina15 commented
> А зачем процедура? Нормально же с функцией было, не? Просто создание времянки там же оставить внутри, а не сюда выносить. Или я недопонимаю логики?

Вот так же было?

```bsl
ПутьКСпискуФайловЗагрузки_Обработанный = ОбработатьСписокФайловЗагрузки(ПутьКСпискуФайловЗагрузки)
```

пусть бы так и оставалось, красиво же. 

Я подумал, что раз временные файлы надо очистить после процедуры, то и создавать надо перед процедурой, а не в ней. Иначе как-то странно получается, вроде при вызове думать о создании файлов не надо, а после надо подумать об удалении. Tempfiles не удаляет же ничего автоматом. Или я не туда смотрел?

2021-06-01 19:35 UTC, EvilBeaver commented
> Я подумал, что раз временные файлы надо очистить после процедуры, то и создавать надо перед процедурой, а не в ней. Иначе как-то странно получается, вроде при вызове думать о создании файлов не надо, а после надо подумать об удалении.

Ну тоже справедливо, с другой стороны. ВременныеФайлы действительно ничего не удаляет, но это я доработаю сами временные файлы, давно хочу, вот как раз и повод будет.

2021-06-01 19:41 UTC, EvilBeaver commented
А вот кстати еще вопрос: а зачем в файле некорректные строки? Может сам файл формировать нормально?

2021-06-01 21:42 UTC, infina15 commented
> Ну тоже справедливо, с другой стороны. ВременныеФайлы действительно ничего не удаляет, но это я доработаю сами временные файлы, давно хочу, вот как раз и повод будет.

Ок, тогда сделаю завтра удаление файлов после функции. Надо только будет запомнить, что после допила tempfiles надо будет убрать это удаление

2021-06-01 21:46 UTC, infina15 commented
> А вот кстати еще вопрос: а зачем в файле некорректные строки? Может сам файл формировать нормально?

В конторе с этим же и столкнулся. Ситуация следующая:
1. Разработчик редактирует модуль формы, вызывает gitsync.
2. Gitsync делает честный коммит, в котором будет один файл с модулем формы (Module.bsl)
3. Если попытаться автоматизировать деплой, то /LoadConfigFromFiles не пронесёт список из одного такого файла, будет ошибка «не найден объект. Да и даже если все файлы конфигурации перечислить в списке, все равно будет ошибка, нельзя вставлять модуль в список файлов. Только xml формы.

2021-06-02 10:51 UTC, EvilBeaver commented
Ну в таком сценарии вообще вопрос к деплою, а не к процедуре загрузки. Кажется, что в таком сценарии никакой обработки файлов вообще не должно быть в методе ЗагрузитьКонфигурациюИзФайлов. Экспортный метод обработки файла пускай этим занимается и управляется со стороны клиента, который знает, что файл у него битый, не по стандарту.

Ведь что получается. метод ЗагрузитьКонфигурациюИзФайлов ждет файл, который точно пролезет в конфигуратор. Это смысл процедуры. Туда нельзя помещать "войну и мир", JPG с корпоративов и строки *.bsl. А коли так, то никакой логики фильтрации метод выполнять не должен и должен принимать файл как есть.

2021-06-02 11:24 UTC, infina15 commented
> 
> 
> Ну в таком сценарии вообще вопрос к деплою, а не к процедуре загрузки. Кажется, что в таком сценарии никакой обработки файлов вообще не должно быть в методе ЗагрузитьКонфигурациюИзФайлов. Экспортный метод обработки файла пускай этим занимается и управляется со стороны клиента, который знает, что файл у него битый, не по стандарту.
> 
> Ведь что получается. метод ЗагрузитьКонфигурациюИзФайлов ждет файл, который точно пролезет в конфигуратор. Это смысл процедуры. Туда нельзя помещать "войну и мир", JPG с корпоративов, и строки *.bsl. А коли так, то никакой логики фильтрации метод выполнять не должен и должен принимать файл как есть.

В том-то и дело, что если выгрузить файлы конфигурации, составить из них список и загрузить эти файлы через /LoadConfigFromFiles, то гарантированно будет ошибка, если есть хотя бы один модуль формы. Поэтому вне зависимости от того откуда вызывается функция /LoadConfigFromFiles, надо править ей входящий список.

2021-06-02 12:18 UTC, infina15 commented
@EvilBeaver так что, переделывать на функцию или закрываем ПР?

2021-06-03 09:46 UTC, EvilBeaver commented
Я бы оставил на месте функцию переделки файла, как раз пригодился Экспорт. А внутри безусловное преобразование бы убрал.

2022-11-03 07:36 UTC, EvilBeaver commented
@infina15 тут как-то замерзло... Может растопим? На чем дело остановилось?

2022-11-03 08:09 UTC, infina15 commented
@EvilBeaver я все же в своем пайплайне накрутил еще несколько костылей, чтобы оно работало хоть как-то.

Например если мы пытаемся изменить одну единственную форму (в -listFiles укажем только эту форму), но в папке с файлами будет вся конфигурация, платформа может ругаться на несовпадение идентификаторов других объектов, которые не относятся к текущему деплою (не указаны в -listFiles). Для решения такой проблемы я оставляю в папке с файлами конфигурации только те объекты, которые идут в текущий деплой. Таким образом у платформы нет возможности видеть эти кривые идентификаторы. Хоть она на них и не должна была смотреть. Черный ящик...

Собственно, все это многообразие сферических костылей в вакууме не оставляют ни единого шанса думать о том что их стоит добавлять в v8runner. Все же это ошибки платформы, о которых надо писать в 1С, а не библиотеки править.

Посему закрываю PR.

2022-11-03 08:09 UTC, closed without merging