Функция запуска проверки конфигурации
oscript-library/v8runner pull request #137
Opened 2022-02-17 08:50 UTC by Golovanoff

Имена проверок сделал такие же, как их видно в конфигураторе при ручном запуске,  но без пробелов и скобочек.
Работает аналогично процедуре ВыполнитьСинтаксическийКонтроль, но можно указать все доступные ключи проверки конфигурации.

Пример вызова проверки:

```
Конфигуратор = Новый УправлениеКонфигуратором;
Конфигуратор.УстановитьКонтекст(СтрокаСоединения, Пользователь, Пароль);

Проверки = Новый Массив();
Проверки.Добавить("Сервер");
Проверки.Добавить("ТолстыйКлиентОбычноеПриложение");
Проверки.Добавить("ПроверкаСуществованияНазначенныхОбработчиков");
Проверки.Добавить("ПоискПустыхОбработчиков");
Проверки.Добавить("РасширеннаяПроверка");

Конфигуратор.ПроверкаКонфигурации(Проверки);
```

2022-02-17 09:16 UTC, EvilBeaver requested changes

2022-02-17 09:16 UTC, EvilBeaver commented on src/v8runner.os
> +	ДопустимыеКлючи.Вставить("ВыполнитьЗаданныеПроверкиДляВсехРасширений", "-AllExtensions");
Может покороче назвать как-то? ПроверкаВсехРасширений/ПроверкаРасширений?

2022-02-17 09:16 UTC, EvilBeaver commented on src/v8runner.os
> +Функция ПроверкаКонфигурации(Проверки, ИмяРасширения = "") Экспорт
Мне кажется, было бы удобнее, чтобы пользователь метода не запоминал все возможные настройки и получал приемлемый результат. Например, есть какой-то метод, который возвращает предзаполненные "Проверки" наиболее употребимым составом проверок.

2022-02-17 09:16 UTC, EvilBeaver commented on src/v8runner.os
> +	ДопустимыеКлючи.Вставить("ВыполнитьЗаданныеПроверкиДляУказанногоРасширения", СтрШаблон("-Extension %1", ИмяРасширения));
1C позволяет проверить только 1 расширение? Кажется, там можно указать несколько расширений к проверке. А значит, АПИ метода может это поддержать

2022-02-17 09:17 UTC, artbear requested changes

2022-02-17 09:17 UTC, artbear commented on src/v8runner.os
> +	ДопустимыеКлючи.Вставить("ВыполнитьЗаданныеПроверкиДляУказанногоРасширения", СтрШаблон("-Extension %1", ИмяРасширения));
эту строку лучше вообще не формировать, если нет расширения.

сейчас при это будет строка -Extension, что приведет к ошибке

2022-02-17 09:17 UTC, artbear commented on src/v8runner.os
> +	ДопустимыеКлючи.Вставить("ПроверкаЛогическойЦелостностиКонфигурации", "-ConfigLogIntegrity");
предлагаю  добавить и английские ключи из Конфигуратора, чтобы были не только русские имена.

в этом случае разработчик сможет быстро скопипастить их из справки Конфигуратора, и ему не придется идти в код в8раннера, чтобы искать правильное наименование

т.е. добавить
`ДопустимыеКлючи.Вставить("-ConfigLogIntegrity", "-ConfigLogIntegrity");`

2022-02-17 09:19 UTC, Golovanoff commented on src/v8runner.os
> +	ДопустимыеКлючи.Вставить("ВыполнитьЗаданныеПроверкиДляУказанногоРасширения", СтрШаблон("-Extension %1", ИмяРасширения));
это только соответствие,  если ключа не будет в массиве,  о и опция в параметры не попадет. А если в массиве есть, а имя не указано - пусть падает

2022-02-17 09:20 UTC, Golovanoff commented on src/v8runner.os
> +	ДопустимыеКлючи.Вставить("ВыполнитьЗаданныеПроверкиДляВсехРасширений", "-AllExtensions");
можно наделать в соответствии сколько угодно записей. я добавил так, как это в конфигураторе у меня называется.

2022-02-17 09:24 UTC, Golovanoff commented on src/v8runner.os
> +Функция ПроверкаКонфигурации(Проверки, ИмяРасширения = "") Экспорт
ну а какие предзаполненные? у меня,  например,  тослтый клиент, у меня свои предзаполненные. у остальных - тонкие клиенты и там свои. ну и есть же старая ВыполнитьСинтаксическийКонтроль, там как раз предзаполненность для всех.

да и мы же не для пользователей пишем, а для суровых бородатых прогеров.

2022-02-17 09:28 UTC, Golovanoff commented on src/v8runner.os
> +Функция ПроверкаКонфигурации(Проверки, ИмяРасширения = "") Экспорт
можно,  наверное,  при пустом массиве ставить проверки такие же, как в конфигураторе по умолчанию ставятся - проверку лог. целостности, поиск некорректных ссылок,  тонкий клиент, сервер и расширенную проверку.
но это будет долгая проверка - у меня при установленной расширенной проверке джоба работает около часа.

2022-02-17 09:33 UTC, artbear commented on src/v8runner.os
> +	ДопустимыеКлючи.Вставить("ВыполнитьЗаданныеПроверкиДляУказанногоРасширения", СтрШаблон("-Extension %1", ИмяРасширения));
насколько я помню, разрешено только одно расширение

2022-02-17 09:35 UTC, artbear commented on src/v8runner.os
> +Функция ПроверкаКонфигурации(Проверки, ИмяРасширения = "") Экспорт
я также хотел предложить, чтобы был публичный метод, возвращающий соответствие с возможными ключами

2022-02-17 09:36 UTC, artbear commented on src/v8runner.os
> +	ДопустимыеКлючи.Вставить("ВыполнитьЗаданныеПроверкиДляУказанногоРасширения", СтрШаблон("-Extension %1", ИмяРасширения));
согласен, вопрос закрыт.

2022-02-17 11:57 UTC, artbear requested changes
еще немного замечаний

2022-02-17 11:57 UTC, artbear commented on src/v8runner.os
> +Функция КлючиПроверкиКонфигурации() Экспорт
а где описание публичной функции? )

2022-02-17 11:57 UTC, artbear commented on src/v8runner.os
> +			КлючЗапуска = ?(НРег(КлючПроверки) = "-extension", СтрШаблон("%1 %2", КлючПроверки, ИмяРасширения), КлючПроверки);
Сонара на тебя нет )
тернарные операторы не юзаем.

2022-02-17 11:57 UTC, artbear commented on src/v8runner.os
> +			КлючЗапуска = ?(НРег(КлючПроверки) = "-extension", СтрШаблон("%1 %2", КлючПроверки, ИмяРасширения), КлючПроверки);
2.1 регистр важен ИМХО 

1С-ка в каких-то версиях ругалась, если ключ в другом регистре.
могли и исправить, конечно.

2 предлагаю явно написать СтрШаблон("-Extension %1", ИмяРасширения)

2022-02-17 11:57 UTC, artbear commented on src/v8runner.os
> +Функция ПроверкаКонфигурации(Проверки, ИмяРасширения = "") Экспорт
нет описания публичной функции

2022-02-17 11:58 UTC, artbear commented on src/v8runner.os
> +Функция ПроверкаКонфигурации(Проверки, ИмяРасширения = "") Экспорт
исправлено. @EvilBeaver закрываем обсуждение?

2022-02-17 15:19 UTC, EvilBeaver commented on src/v8runner.os
> +Функция ПроверкаКонфигурации(Проверки, ИмяРасширения = "") Экспорт
Как именно исправлено? где?

2022-02-21 07:35 UTC, artbear commented on src/v8runner.os
> +			КлючЗапуска = ?(НРег(КлючПроверки) = "-extension", СтрШаблон("%1 %2", КлючПроверки, ИмяРасширения), КлючПроверки);
сонар бсл и на обычный тернарник ругается. и я с ним согласен, код гораздо менее читабелен.

2022-02-21 07:36 UTC, artbear commented on src/v8runner.os
> +Функция ПроверкаКонфигурации(Проверки, ИмяРасширения = "") Экспорт
> Как именно исправлено? где?

@EvilBeaver исправлено в https://github.com/oscript-library/v8runner/pull/137/commits/c26863135376d4ab18ef5b1b70737ca1a2ed2ee5

2022-02-21 12:28 UTC, nixel2007 commented on src/v8runner.os
> +			КлючЗапуска = ?(НРег(КлючПроверки) = "-extension", СтрШаблон("%1 %2", КлючПроверки, ИмяРасширения), КлючПроверки);
Запрет тернарника по умолчанию выключен.

2022-02-22 12:12 UTC, merged

2022-03-06 16:10 UTC, artbear commented
Эх, ну почему в мастер-то?? теперь девелоп отстал от мастера (