Дополнительные параметры, подмешиваемые к любой команде + исправление мелких проблем
oscript-library/v8runner pull request #139
Opened 2022-03-06 16:47 UTC by artbear

2022-03-14 17:09 UTC, otymko commented on src/v8runner.os
> +// Устанавливаются дополнительные параметры, которые добавляются (подмешиваются) к очередной выполняемой команде
@artbear может тогда вместо "Устанавливаются" -> "Установить" или "Устанавливает"?

2022-03-14 17:09 UTC, otymko commented on src/v8runner.os
> +//
@artbear небольшой пример здесь был бы кстати

2022-03-14 17:09 UTC, otymko commented on src/v8runner.os
> +			ПараметрыЗапуска.Добавить(ДопПараметр);
@artbear контроль уникальности отдаем пользователям либы?

2022-03-14 17:11 UTC, otymko commented
@artbear а в текущем проекте нет задачи по этому ПР?

2022-03-15 11:59 UTC, artbear commented
> @artbear а в текущем проекте нет задачи по этому ПР?

такой задачи нет.

2022-03-15 12:07 UTC, artbear commented on src/v8runner.os
> +			ПараметрыЗапуска.Добавить(ДопПараметр);
да, им отдаем.

я думал о контроле дублей, но простым способом его не сделать, решил отдать запускателям.

2022-03-15 12:08 UTC, artbear commented on src/v8runner.os
> +//
сделано.

2022-03-18 09:49 UTC, artbear commented on src/v8runner.os
> +// Устанавливаются дополнительные параметры, которые добавляются (подмешиваются) к очередной выполняемой команде
@otymko сделано

2022-03-22 10:25 UTC, EvilBeaver commented
@artbear мне не нравятся универсальные апи SELECT * FROM *

Можешь привести пример, что такое "дополнительный параметр, примешиваемый к любой команде"?

2022-03-22 10:27 UTC, EvilBeaver requested changes

2022-03-22 10:27 UTC, EvilBeaver commented on tests/v8runner-test.os
> +	УправлениеКонфигуратором.ВыполнитьКоманду(УправлениеКонфигуратором.ПолучитьПараметрыЗапуска());
ВыполнитьКоманду получает на вход массив аргументов. В этот массив и должны добавляться "доп. параметры". А так они установлены где-то выше по коду, в месте вызова никак не ясно, что вызывается.

Я бы предложил какой-то билдер параметров, а не универсальный флажок где-то выше по стеку

2022-03-22 10:28 UTC, EvilBeaver commented on src/v8runner.os
> +			ПараметрыЗапуска.Добавить(ДопПараметр);
Билдер коллекции параметров нужен. Вот такая глобальная коллекция, за которой надо следить - мне не нравится.

2022-03-24 09:57 UTC, artbear commented
@EvilBeaver предложил следующий вариант
```
Для расширений предлагаю глобальное состояние, как для пароля. Установили контекст, указали, что командв будет для расширения.
Т.е. не глобальное "дополнительное что угодно", а предметное для расширения
```

мой ответ: предварительно такой вариант для расширений подойдет
над другими кейсами еще подумаю

текущий ПР закрываю.

2022-03-24 09:57 UTC, closed without merging

2022-11-03 07:38 UTC, EvilBeaver commented
@artbear что там у нас для контекста команды под расширения в итоге получилось? Вот в #147 бы пригодилось