Возможность формирования произвольных команд из внешних скриптов
oscript-library/v8runner pull request #156
Opened 2023-09-18 19:49 UTC by 240596448

Экспортная `ВыполнитьКоманду` не имеет смысла без `СтандартныеПараметрыЗапускаКонфигуратора`
Чтобы сформировать произвольную команду требуется две экспортные функции.
```
Параметры = Конфигуратор.СтандартныеПараметрыЗапускаКонфигуратора();
Параметры.Добавить("/КлючКоторогоНетВБиблиотеке"); // мои необычные ключи
Конфигуратор.ВыполнитьКоманду(Параметры);
```

2023-09-20 10:44 UTC, EvilBeaver commented
Не соглашусь. Первый метод это хелпер. Вызов ``ВыполнитьКоманду(Параметры)`` не требует предварительного вызова ``СтандартныеПараметрыЗапускаКонфигуратора``.

Кроме того, я не совсем понял, что именно предлагается реализовать в рамках данного issue.

2023-09-20 10:46 UTC, EvilBeaver requested changes

2023-09-20 10:46 UTC, EvilBeaver commented on src/v8runner.os
> +Функция СтандартныеПараметрыЗапускаКонфигуратора() Экспорт
Раз это экспорт, то требуется документирующий комментарий для метода. Что он делает, что возвращает и зачем применять

2023-09-20 10:53 UTC, 240596448 commented
Когда СтандартныеПараметрыЗапускаКонфигуратора недоступен - мне приходится его функциональность полностью продублировать где-то у себя снаружи.

Например, в библиотеке не реализована выгрузка по файлом из списка объектов.
При этом я мог бы в своей обертке реализовать это тремя строчками (пример в первом сообщении). Не хватает лишь стандартных параметров из СтандартныеПараметрыЗапускаКонфигуратора, которые я и так заполняю при создании класса.
Сейчас приходится иметь два класса: "либа" и "частичная копипаста" для произвольной команды.

2023-09-21 08:57 UTC, EvilBeaver commented
@240596448 просьба добавить комментарий для экспортного метода и вливаем

2023-09-25 20:42 UTC, 240596448 commented on src/v8runner.os
> +Функция СтандартныеПараметрыЗапускаКонфигуратора() Экспорт
Добавил

2023-09-26 08:40 UTC, merged