Реализован параметр ПутьКСпискуОбъектовВыгрузки для выгрузки в файлы
oscript-library/v8runner pull request #175
Opened 2024-12-30 10:04 UTC by vkislitsin

Для методов ВыгрузитьКонфигурациюВФайлы() и ВыгрузитьРасширениеВФайлы() добавлен параметр ПутьКСпискуОбъектовВыгрузки,  позволяющий задать список объектов, подлежащих выгрузке.
Транслируется в параметр -listFile команды /DumpConfigToFiles.
Issue: https://github.com/oscript-library/v8runner/issues/174#issue-2762955011

2025-01-02 09:24 UTC, EvilBeaver requested changes
Просьба заменить табы на 4 пробела

2025-01-02 09:24 UTC, EvilBeaver commented on src/v8runner.os
> +//											Указываемый файл должен удовлетворять следующим требованиям:
Какой-то очень большой отступ, полагаю, что это табы, а не пробелы. Давайте заменим на пробелы?

2025-01-02 09:24 UTC, EvilBeaver commented on src/v8runner.os
> +									  Знач ПутьКФайлуВерсийДляСравнения = "",
И здесь тоже

2025-01-02 09:24 UTC, EvilBeaver commented on src/v8runner.os
> +
И во всем файле

2025-01-05 17:52 UTC, vkislitsin commented
> Просьба заменить табы на 4 пробела
Заменил табы на пробелы, где потребовалось.

2025-01-11 06:35 UTC, EvilBeaver approved these changes
Спасибо!

2025-01-11 06:36 UTC, merged